### ISSUE TITLE
Improve handling of tibbles with invalid column names

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#2401]
- [ ] filter (#2351): NA or empty name
- [ ] join (#2353): duplicate name
- [ ] join (#2447): appending suffix
- [ ] hybrid evaluation: NA, empty, or duplicate name
    - should give a warning on access
- [ ] group_by: ???
- [ ] select(): should give a warning
- [ ] mutate(): should give a warning with duplicate names
- [ ] summarise(): should give a warning with duplicate names

CC @hadley.

**Comment by hadley** [comment]
I don't think we need to worry about this for databases as the database will enforce it.

**Comment by krlmlr** [comment]
After #2311.

**Comment by nalimilan** [comment]
I'm curious what rule you have in mind regarding duplicate column names in general. Currently `cbind` allows creating tibbles with duplicate column names, without a warning (just like data frames). Is this intended?

One of the reasons I am asking is because we're considering making it impossible to create data frames with duplicate column names in Julia (https://github.com/JuliaData/DataFrames.jl/pull/1308), so I wonder whether there could be reasons to allow them.

**Comment by hadley** [comment]
@nalimilan I think my current position is that creating a duplicate column name should always be an error (but we don't always have control over the code in order to make it an error)

**Comment by nalimilan** [comment]
OK, thanks, we're on the same page then!

**Comment by krlmlr** [comment]
We should do this for a major release to avoid accidental breakages of code that worked before (one way or another).

**Comment by romainfrancois** [comment]
#2311 is essentially done, @krlmlr let's talk about this

**Comment by krlmlr** [comment]
http://rpubs.com/krlmlr/dplyr-empty-name, http://rpubs.com/krlmlr/dplyr-duplicate-name

**Comment by krlmlr** [comment]
- Disallow duplicate names (existing behavior)
- Allow empty names (fix `filter()` and `arrange()`)
- Advise user to do column selection when importing

**Comment by krlmlr** [comment]
It looks like we're now getting the check for columns with empty name for free, when creating the data mask in `DataMask::DataMask()`. Is it worth it to enhance the implementation of the data mask to ignore columns with empty name, or at least throw a more informative error?

Joins aren't affected, we can join in the presence of empty names, even join by an unnamed column. Duplicate names are detected and break the join.

**Comment by krlmlr** [comment]
Looked at it again. Do we need to take efforts to support tibbles with empty column names? If not, we're good here.

``` r
library(tidyverse)

tbl <-
  list(1:3, b = 4:6) %>%
  as_tibble(.name_repair = "minimal")

tbl
#> # A tibble: 3 x 2
#>      ``     b
#>   <int> <int>
#> 1     1     4
#> 2     2     5
#> 3     3     6

tbl %>%
  slice(1)
#> Error in slice_impl(.data, quo): attempt to use zero-length variable name
```

<sup>Created on 2019-02-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment]
I don't think we need to support zero-width column names.
