### ISSUE TITLE
Breaking (and other) changes for dplyr 0.9.0

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#2790]
I'd like to suggest that we break the things we want to break very early in the release cycle. We should only break things where there is a clearly better alternative in the existing CRAN version. This could be done in a separate pull request first, with early notification to the downstream dependencies.

New interfaces should not break existing ones, we can mark them as deprecated in the docs and start breaking them in the version after that. This includes changes in behavior.

This meta-issue could collect the scheduled breakages. Off the top of my head, this includes:

- [ ] `all.equal()` (#2751)
- [ ] Warn if `vars` attribute is a list (https://github.com/tidyverse/dplyr/pull/2786#discussion_r116718129)
- [ ] Deprecation warnings in `summarise_each()` and `mutate_each()` (#2791)
- [x] Remove dbplyr from .travis.yml and appveyor.yml
- [x] Finally remove `rbind_list()` and `rbind_all()` (https://github.com/tidyverse/dplyr/pull/2828#issuecomment-305162664)
- [ ] Add api_roclet to DESCRIPTION (and pkgapi to Suggests) (https://github.com/tidyverse/dplyr/pull/2805#issuecomment-305188732)
- [ ] Revert #3055
- [ ] Change warning to error in #3140
- [ ] Change default of `na_matches` argument
- [ ] Throw an error when trying to access variables through a leaked data mask (https://github.com/tidyverse/dplyr/pull/3443#issuecomment-374180030)
- [ ] Order of variables, #3481
- [ ] Raise error when accessing hybrid functions not on the search path (https://github.com/tidyverse/dplyr/pull/3458#issuecomment-376101368)
- [ ] Implement only methods for `data.frame`, with an internal `reconstruct()` that restores the `"tbl_df"` class if the input had it (#3429)
- [x] Tidy grouped data attributes (#3489)
- [ ] Fail if matrix is passed to `if_else()` and `case_when()` (#3256)

**Comment by hadley** [comment]
We'll reserve breaking API changes for 0.9.0.  Maybe it would be better to have a label than a meta issue?

**Comment by krlmlr** [comment]
I'm not sure. They lie around here peacefully, waiting patiently for their time to come...

**Comment by cboettig** [comment]
>  - [ ] Change default of `na_matches` argument

👏 🙏

**Comment by hadley** [comment]
- `all.equal()` (#2751) - done.
- Warn if `vars` attribute is a list - likely to be out of date since we'll be reconsidering the class structure anyway
- Deprecation warnings in `summarise_each()` and `mutate_each()` - now #4655
- Add api_roclet to DESCRIPTION - still not convinced this technique is mature enough
- Revert #3055 - now #4656
- Change warning to error in #3140 - also #4656
- Change default of `na_matches` argument - I no longer believe this is a good idea
- Throw an error when trying to access variables through a leaked data mask (https://github.com/tidyverse/dplyr/pull/3443#issuecomment-374180030) - too vague
- Order of variables, #3481 - milestone added
- Raise error when accessing hybrid functions not on the search path (https://github.com/tidyverse/dplyr/pull/3458#issuecomment-376101368) - hybrid functions are no more
- Implement only methods for `data.frame`, with an internal `reconstruct()` that restores the `"tbl_df"` class if the input had it (#3429) - @lionel is working on it
- Fail if matrix is passed to `if_else()` and `case_when()` (#3256) - now problem of funs package
