### ISSUE TITLE
dplyr 1.1.0 revdep tracker

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/dplyr#6262]

**Comment by hadley** [comment]
I'll take these ones:


## `na_if()` vctrs update #6329
- [ ] circumplex: Doing `dplyr::na_if(., "NaN")` on a double vector, I assume to replace `NaN` with `NA`?
- [ ] forestmangr: Doing `dplyr::na_if(., 0)` where `.` is a tibble, I guess expecting each column to get na-if'd?
- [ ] hlaR: Expecting a character `y` to be compatible with integer `x`
- [ ] huito: "`y` <character> to match type of `x` <data.frame>" with `na_if()`, same as forestmangr?
- [ ] itraxR: Looks like CRAN version had a problem that was fixed here in dev version. Related to `na_if()` on a data frame https://github.com/tombishop1/itraxR/commit/5de1717f60dffc134e20fed25344db0dacf37f91
- [ ] JumpeR: Another "Can't convert `y` <double> to match type of `x` <data.frame>"
- [ ] naniar: Another "Can't convert `y` <double> to match type of `x` <tbl_df>" in the `replace-with-na.Rmd` vignette
- [ ] skater: Looks like calling `na_if(<chr>, 0)` in a vignette on column `dadid`
- [ ] suddengains: Looks like `na_if(<dbl>, "-Inf")` which is weird because `-Inf == -Inf` does return `TRUE`
- [ ] SwimmeR: Another: "Can't convert `y` <character> to match type of `x` <data.frame>."

**Comment by DavisVaughan** [comment]
## Join `check_dots_unused()` (our fault) #6599 
- [ ] disk.frame `anti_join(.x, .y, by = by, copy = copy, ..., overwrite = overwrite)`
- [ ] table.express `left_join.ExprBuilder(roll =  #TRUE)`
- [x] tidytree: https://github.com/YuLab-SMU/tidytree/pull/29 this one had a bug too

**Comment by lionel-** [comment]
## `nth()`, `first()`, `last()` vctrs update #6331
- [x] confoundr: "Can't convert `default` <character> to match type of `x` <double>", `first(x, default = "NA")` with double `x` - https://github.com/jwjackson/confoundr/pull/3
- [x] divseg: Does `dplyr::first(dplyr::cur_data())` expecting to get the first col of the data frame? Should use `pull()`. - https://github.com/christopherkenny/divseg/pull/1
- [x] finnts: `dplyr::filter(Date==max(Date)) %>% dplyr::last()` on a df where they should have used `pull(-1)` - https://github.com/microsoft/finnts/pull/117
- [x] FRK: Not sure, possibly related but hard to diagnose - https://github.com/andrewzm/FRK/pull/7
- [x] janitor: `dplyr::last(dat)` on a data frame expecting last column, should use `pull()` - https://github.com/sfirke/janitor/pull/491
- [x] questionr: Broken because of janitor
- [x] tidygraph: `dplyr::count() %>% dplyr::first()` on a data frame, expecting first column, should use `pull()` - https://github.com/thomasp85/tidygraph/pull/168


# `select_vars()` deprecation #6389 
- [x] extdplyr: `dplyr::select_vars(colnames(data), ...)` - No online repo, sent mail with a link to https://github.com/lionel-/extdplyr/commit/a3cc769236c4a14ab72f377e7904414a9a1a86f0
- [x] NobBS: No online repo, sent mail with a link to https://github.com/lionel-/NobBS/commit/d7e4607fcb55473f42add76eb03109a26180d04b

## `n_distinct()` doesn't allow 0 args
- [x] arrow: `test-dplyr-summarize.R:301` - https://github.com/apache/arrow/pull/14948

## Join `check_dots_unused()` (actual bug) (lionel)
- [x] iNZightTools: calling `anti_join()` with `suffix` arg but that doesn't exist - https://github.com/iNZightVIT/iNZightTools/pull/196
- [ ] lillies: `all.x` arg that doesn't exist `dplyr::left_join(LYL, ages_onset, by = "age", all.x = T)`
- [ ] mudata2: `prefix` arg that doesn't exist, supposedly meant `suffix`? 
- [ ] overviewR: `by.x` and `by.y` args that don't exist
- [ ] tidyquery: Looks like they might be calling `anti_join()` or something like it with `suffix=`, which doesn't exist. Probably will need to open an issue and let them fix it.
- [ ] dtrackr: Calls `semi_join()` with `suffix=` argument. Probably need to let them fix.

**Comment by lionel-** [comment]
New problems revealed in revdep checks of #6550:

## New exported `where()` function causes an import conflict

Caused by #6609. `where()` is also exported by ape and imager packages.

- [ ] ggmuller
- [ ] LARGB
- [ ] treeplyr

**Comment by DavisVaughan** [comment]
3 more detected only by CRAN's checks. We aren't sure how they slipped through ours.

- [x] DecomposeR - https://github.com/cran/DecomposeR/pull/1 and email
- [x] eHDPrep - https://github.com/overton-group/eHDPrep/pull/3 
- [x] SIPmg - https://github.com/ZielsLab/SIPmg/pull/1

**Comment by hadley** [comment]
On CRAN 🥳
