### ISSUE TITLE
dplyr 1.1.1 revdep tracker

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/dplyr#6767]
## `relationship` warning
- [x] comperes https://github.com/echasnovski/comperes/pull/8
- [x] dm: https://github.com/cynkra/dm/pull/1806
- [x] exuber https://github.com/kvasilopoulos/exuber/pull/24
- [x] tidytransit https://github.com/r-transit/tidytransit/pull/197

## `dplyr:::check_name()` renamed 
- [x] arrow: https://github.com/apache/arrow/issues/34366

---

## Can't superclass `data.frame` now that `group_data.data.frame()` uses `vec_size()` https://github.com/tidyverse/dplyr/pull/6736

Reverted in https://github.com/tidyverse/dplyr/pull/6768, even though these packages really should be fixed

- [x] autoReg: https://github.com/cardiomoon/autoReg/pull/2
- [x] mapping
- [x] NetworkExtinction
- [x] onemap
- [x] PupillometryR

## False alarms
- [x] rgho
- [x] isotracer, fails locally in the same spot with CRAN and dev dplyr
- [x] vctrs: circular import that will be resolved with CRAN vctrs 0.5.3
- [x] missCompare: fails in a simulation test that looks related to Hmisc
